# Generated by Django 4.1.6 on 2023-02-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_prov_name', models.CharField(max_length=30)),
                ('ser_prov_username', models.CharField(max_length=30)),
                ('ser_prov_email_address', models.EmailField(max_length=70)),
                ('ser_prov_phone_number', models.CharField(max_length=30)),
                ('ser_prov_password', models.CharField(max_length=100)),
                ('ser_prov_service_country', models.CharField(max_length=30)),
                ('ser_prov_service_city', models.CharField(max_length=30)),
                ('ser_prov_service_area', models.CharField(max_length=30)),
            ],
        ),
    ]
