# Generated by Django 4.1.6 on 2023-04-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gigs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gig_title', models.CharField(max_length=30)),
                ('gig_category', models.CharField(max_length=30)),
                ('gig_sub_category', models.EmailField(max_length=30)),
                ('gig_search_tags', models.CharField(max_length=60)),
                ('gig_package_detail_basic_name', models.CharField(max_length=30)),
                ('gig_package_detail_standard_name', models.CharField(max_length=30)),
                ('gig_package_detail_premium_name', models.CharField(max_length=30)),
                ('gig_package_detail_basic_detail', models.CharField(max_length=100)),
                ('gig_package_detail_standard_detail', models.CharField(max_length=100)),
                ('gig_package_detail_premium_detail', models.CharField(max_length=100)),
                ('gig_package_detail_basic_delivery_time', models.CharField(max_length=3)),
                ('gig_package_detail_standard_delivery_time', models.CharField(max_length=30)),
                ('gig_package_detail_premium_delivery_time', models.CharField(max_length=30)),
                ('gig_package_detail_basic_price', models.CharField(max_length=30)),
                ('gig_package_detail_standard_price', models.CharField(max_length=30)),
                ('gig_package_detail_premium_price', models.CharField(max_length=30)),
                ('gig_package_detail_basic_detail_brief', models.CharField(max_length=300)),
                ('gig_package_detail_standard_detail_brief', models.CharField(max_length=300)),
                ('gig_package_detail_premium_detail_brief', models.CharField(max_length=300)),
                ('gig1_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('gig2_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('gig3_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('ser_prov_service_country', models.CharField(max_length=30)),
                ('ser_prov_service_city', models.CharField(max_length=30)),
                ('ser_prov_service_area', models.CharField(max_length=30)),
            ],
        ),
    ]
