# Generated by Django 4.1.6 on 2023-04-03 19:51

import catering.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0002_gigs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigs',
            name='gig_package_detail_basic_detail_brief',
        ),
        migrations.RemoveField(
            model_name='gigs',
            name='gig_package_detail_premium_detail_brief',
        ),
        migrations.RemoveField(
            model_name='gigs',
            name='gig_package_detail_standard_detail_brief',
        ),
        migrations.RemoveField(
            model_name='gigs',
            name='ser_prov_service_area',
        ),
        migrations.RemoveField(
            model_name='gigs',
            name='ser_prov_service_city',
        ),
        migrations.RemoveField(
            model_name='gigs',
            name='ser_prov_service_country',
        ),
        migrations.AddField(
            model_name='gigs',
            name='gig_package_details',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='gigs',
            name='gig_user',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='gigs',
            name='gig_vedio',
            field=models.FileField(default='', upload_to='usr_video/%y', validators=[catering.validators.file_size]),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='gig1_image',
            field=models.ImageField(default='', upload_to='usr_img/%y'),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='gig2_image',
            field=models.ImageField(default='', upload_to='usr_img/%y'),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='gig3_image',
            field=models.ImageField(default='', upload_to='usr_img/%y'),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='gig_category',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='gig_package_detail_basic_delivery_time',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='gig_package_detail_basic_detail',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='gig_package_detail_basic_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='gig_package_detail_basic_price',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='gig_package_detail_premium_delivery_time',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='gig_package_detail_premium_detail',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='gig_package_detail_premium_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='gig_package_detail_premium_price',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='gig_package_detail_standard_delivery_time',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='gig_package_detail_standard_detail',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='gig_package_detail_standard_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='gig_package_detail_standard_price',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='gig_search_tags',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='gig_sub_category',
            field=models.EmailField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='gig_title',
            field=models.CharField(default='', max_length=30),
        ),
    ]
