# Generated by Django 4.1.6 on 2023-04-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0003_remove_gigs_gig_package_detail_basic_detail_brief_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigs',
            name='gig1_image',
            field=models.ImageField(default='', upload_to='user_images/%y'),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='gig2_image',
            field=models.ImageField(default='', upload_to='user_images/%y'),
        ),
        migrations.AlterField(
            model_name='gigs',
            name='gig3_image',
            field=models.ImageField(default='', upload_to='user_images/%y'),
        ),
    ]
