# Generated by Django 4.1.6 on 2023-04-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0004_alter_gigs_gig1_image_alter_gigs_gig2_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigs',
            name='gig3_image',
            field=models.ImageField(default='', upload_to='user_images/%yq'),
        ),
    ]
