# Generated by Django 4.1.6 on 2023-05-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0007_alter_gigs_gig1_image_alter_gigs_gig2_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigs',
            name='gig_city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='gigs',
            name='gig_country',
            field=models.CharField(default='', max_length=100),
        ),
    ]
